### ISSUE TITLE
Time Syncing issue

### ISSUE THREAD

**Issue by shalalalatuzki** [shiffman/Most-Pixels-Ever-Processing#63]
dear shiffman
I run mpeTest example in  MPE library,  It runs for a while and then The circles on the screen stop moving.
I try to use MPE in my project, I got into the same trouble,I don't know how to deal with it.  *~*

**Comment by shalalalatuzki** [comment]
I run mpeTest 
one of instance shows error
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at processing.app.Util.unzipEntry(Util.java:648)
	at processing.app.Util.unzip(Util.java:635)
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:112)
	at processing.app.contrib.ContributionManager$2.run(ContributionManager.java:271)
	at java.lang.Thread.run(Thread.java:748)
